- name: Deploy Configuration File
  hosts: localhost
  connection: local
  become: yes  
  vars_files:
    - vars.yml

  tasks:
    - name: Create the instance directory
      file:
        path: {{ instance.path }}
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Generate configuration file
      template:
        src: "../templates/config.j2"
        dest: {{ instance.path }}/config.conf"
        owner: root
        group: root
        mode: '0644'

