- name: Deploy Python application using wheel file
  hosts: localhost
  connection: local
  become: true 
  vars:
    wheel_file_name: "Example-1.1.1-py3-none-any.whl"  
    wheel_file_path: "/home/ec2-user/AnsibleAssessement/{{ wheel_file_name }}"
    virtualenv_path: "/opt/example"

  tasks:
    # Task 1: Install virtualenv if not already present
    - name: Install virtualenv
      pip:
        name: virtualenv
        state: present

    # Task 2: Create Python virtual environment
    - name: Create virtual environment
      command: virtualenv {{ virtualenv_path }}
      args:
        creates: "{{ virtualenv_path }}"

    # Task 3: Install Python application from wheel file
    - name: Install Python application from wheel file
      pip:
        name: "{{ wheel_file_path }}"
        virtualenv: "{{ virtualenv_path }}"
        state: present

    # Task 4: Optionally, restart application services or perform other necessary tasks
    - name: Restart application service
      systemd:
        name: python
        state: restarted
      become: true

