- name: Configure CA certificates, install custom CA, and deploy Python application
  hosts: 172.31.63.50
  become: true  

  vars_files:
    - vault.yml  

  tasks:
    # Task 1: Configure standard CA certificates
    - name: Install standard CA certificates
      package:
        name: ca-certificates
        state: latest
      tags: 
        - ca_certificates

    # Task 2: Install custom CA certificates using private key from vault
    - name: Install custom CA certificates
      copy:
        src: CA1.crt  
        dest: /usr/local/share/ca-certificates/CA1.crt
      notify: Update CA certificates
      tags:
        - custom_ca_certificates

    # Task 3: Notify handler to update CA certificates
  handlers:
    - name: Update CA certificates
      shell: update-ca-certificates
      async: 45
      poll: 0

